### ISSUE TITLE
npm install throws a warning for JSV

### ISSUE THREAD

**Issue by ritesh-pandey** [fusioncharts/larry#10]
`npm WARN package.json JSV@4.0.2 'repositories' (plural) Not supported. Please pick one as the 'repository' field`

Any idea how to fix this?

**Comment by shamasis** [comment]
You cannot. It is an issue with `JSV` module. Try upgrading the module if a new version exists and change `package.json` to that version. Then, after running larry tests if the warning is gone then it should be fixed.

**Comment by shamasis** [comment]
I just checked - https://github.com/garycourt/JSV/blob/master/package.json. The latest release of JSV still has this issue. Closing.
