### ISSUE TITLE
for-in loop is used for iterating over array

### ISSUE THREAD

**Issue by ritesh-pandey** [fusioncharts/larry#8]

**Comment by nullifiedaccount3** [comment]
Can you please elaborate the problem?

**Comment by shamasis** [comment]
@bhargav3 you might want to refer this: http://stackoverflow.com/questions/500504/why-is-using-for-in-with-array-iteration-such-a-bad-idea

> The for-in statement by itself is not a "bad practice", however it can be mis-used, for example, to iterate over arrays or array-like objects.
> The purpose of the for-in statement is to enumerate over object properties, this statement will go up in the prototype chain, enumerating also inherited properties, thing that sometimes is not desired.
> Also, the order of iteration is not guaranteed by the spec., meaning that if you want to "iterate" an array object, with this statement you cannot be sure that the properties (array indexes) will be visited in the numeric order.

**Comment by shamasis** [comment]
PR:13 addresses this issue partly. Further improvement will arrive with code refactor. Closing. Thank you @ritesh-pandey
