### ISSUE TITLE
Too many open file descriptors. Possible reason for ulimit issue.

### ISSUE THREAD

**Issue by ritesh-pandey** [fusioncharts/larry#9]
lib.js 

openSync method opens a file but it closed no where. This might lead to lot of open file handlers.

**Comment by nullifiedaccount3** [comment]
Thanks for reporting. This shall be patched soon. Do you have a way to fix it?

**Comment by shamasis** [comment]
@bhargav3 - in `lib.js:341` I can see`fs.openSync(destination, "w");` is being used. From the looks of it, I am sure why is this done since nothing is being done with the opened stream. :-/

@ritesh-pandey am I on the right line of thoughts?

**Comment by ritesh-pandey** [comment]
@shamasis Yes. As soon as I put a `fs.close(fileDescriptor)` the release script could run on `ulimit -n` as low as 1000.

**Comment by shamasis** [comment]
@ritesh-pandey - you are correct, I also see that `lstatSync`, etc are being done a number of times. By organising the logic we can get `ulimit` to be reduced further. But to begin, let us fix this. Will you send PR?

**Comment by shamasis** [comment]
PR:11 and PR:12 addresses this issue partly. Further improvement will arrive with code refactor. Closing. Thank you @ritesh-pandey
